In [11]:
import numpy as np

In [13]:
data = np.random.randn(2, 3)

In [14]:
data


array([[-1.53198935,  1.54158524, -1.03089667],
       [ 0.05775008,  1.4122896 ,  0.79946703]])

In [15]:
data*10


array([[-15.31989351,  15.4158524 , -10.30896667],
       [  0.57750076,  14.12289601,   7.99467034]])

In [16]:
data + data

array([[-3.0639787 ,  3.08317048, -2.06179333],
       [ 0.11550015,  2.8245792 ,  1.59893407]])

In [17]:
data.shape

(2, 3)

In [18]:
data.dtype

dtype('float64')

In [19]:
data1 = [6,7.5,8,9,2]

In [20]:
arr1 = np.array(data1)

In [40]:
arr1
arr1.ndim

1

In [22]:
data2 = [[1, 2, 3, 5, 7],[9, 10, 11, 12, 13]]

In [23]:
arr2 = np.array(data2)

In [24]:
arr2

array([[ 1,  2,  3,  5,  7],
       [ 9, 10, 11, 12, 13]])

In [25]:
arr2.ndim

2

In [26]:
arr2.shape

(2, 5)

In [28]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [30]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [31]:
np.empty((2, 3, 2))

array([[[  1.13635099e-322,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [33]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)

In [38]:
arr1.dtype

dtype('float64')

In [39]:
arr2.dtype

dtype('int32')

In [41]:
arr = np.array([1, 2, 3, 4, 5])

In [42]:
arr.dtype

dtype('int32')

In [45]:
float_arr = arr.astype(np.float64)

In [46]:
arr.dtype

dtype('int32')

In [47]:
float_arr

array([ 1.,  2.,  3.,  4.,  5.])

In [48]:
float_arr.dtype

dtype('float64')

In [49]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [50]:
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [55]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [56]:
numeric_string= np.array(['1.25', '6.37', '-9.6'])

In [57]:
numeric_string.astype(np.float)

array([ 1.25,  6.37, -9.6 ])

In [58]:
int_array = np.arange(10)

In [60]:
calibers = np.array([0.22, .270, .357, .380, .55, .66], dtype=np.float64)

In [62]:
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [63]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [64]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [65]:
arr*arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [66]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [67]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [68]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [69]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [70]:
arr2

array([[  0.,   4.,   1.],
       [  7.,   2.,  12.]])

In [71]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

In [72]:
arr = np.arange(10)

In [73]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr[5]

5

In [75]:
arr[5:8]

array([5, 6, 7])

In [76]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr[5:8] = 12

In [78]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [79]:
arr_slice = arr[5:8]

In [80]:
arr_slice

array([12, 12, 12])

In [81]:
arr_slice[1]=12345

In [82]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [83]:
arr_slice[:] = 64

In [84]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [85]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [86]:
arr2d[2]

array([7, 8, 9])

In [87]:
arr2d[1][2]

6

In [88]:
arr2d[1,2]

6

In [116]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[ [7, 8, 9], [10, 11, 12]]])

In [117]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [118]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
old_values = arr3d[0].copy()

In [120]:
arr3d[0] = 42

In [121]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [122]:
arr3d[1, 0]

array([7, 8, 9])

In [123]:
arr3d[1, 1]

array([10, 11, 12])

In [125]:
x = arr3d[1]

In [126]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [127]:
x[0]

array([7, 8, 9])

In [128]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [129]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [130]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
arr2d[:2, 1: ]

array([[2, 3],
       [5, 6]])

In [133]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [134]:
arr[:2]

array([0, 1])

In [135]:
arr[2:]

array([ 2,  3,  4, 64, 64, 64,  8,  9])

In [136]:
arr[1:]

array([ 1,  2,  3,  4, 64, 64, 64,  8,  9])

In [141]:
arr2d[1, :2]

array([4, 5])

In [146]:
arr2d[:2, 2]

array([3, 6])

In [3]:
import numpy as np

In [19]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [20]:
data = np.random.randn(7,4)

In [21]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [22]:
data

array([[ 1.188074  , -0.53145209, -1.23693217,  0.26877998],
       [ 0.99925326,  0.49916807, -1.05332279, -0.56539842],
       [-1.56108389, -1.4086936 , -0.79554636,  0.25362799],
       [ 0.50428216,  0.51586907,  0.13764165, -0.95989814],
       [-1.99702856,  0.87254978, -0.800893  ,  0.82905441],
       [-0.05975382,  0.23019908,  0.69965787, -0.4031319 ],
       [ 1.55178949, -0.05616908, -1.34937113, -0.82602407]])

In [23]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [24]:
data[names == 'Bob']

array([[ 1.188074  , -0.53145209, -1.23693217,  0.26877998],
       [ 0.50428216,  0.51586907,  0.13764165, -0.95989814]])

In [25]:
data[names == 'Bob', 2:]

array([[-1.23693217,  0.26877998],
       [ 0.13764165, -0.95989814]])

In [26]:
data[names == 'Bob', 3]

array([ 0.26877998, -0.95989814])

In [27]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [28]:
data[~(names == 'Bob')]

array([[ 0.99925326,  0.49916807, -1.05332279, -0.56539842],
       [-1.56108389, -1.4086936 , -0.79554636,  0.25362799],
       [-1.99702856,  0.87254978, -0.800893  ,  0.82905441],
       [-0.05975382,  0.23019908,  0.69965787, -0.4031319 ],
       [ 1.55178949, -0.05616908, -1.34937113, -0.82602407]])

In [39]:
cond = (names == 'Bob')

In [40]:
data[~cond]

array([-0.05975382,  0.23019908,  0.69965787, -0.4031319 ])

In [51]:
mask = ((names == 'Bob')| (names == 'Joe'))

In [52]:
mask

True

In [55]:
data[mask]

array([[[ 1.188074  , -0.53145209, -1.23693217,  0.26877998],
        [ 0.99925326,  0.49916807, -1.05332279, -0.56539842],
        [-1.56108389, -1.4086936 , -0.79554636,  0.25362799],
        [ 0.50428216,  0.51586907,  0.13764165, -0.95989814],
        [-1.99702856,  0.87254978, -0.800893  ,  0.82905441],
        [-0.05975382,  0.23019908,  0.69965787, -0.4031319 ],
        [ 1.55178949, -0.05616908, -1.34937113, -0.82602407]]])

In [56]:
data[data < 0] = 0

In [57]:
data

array([[ 1.188074  ,  0.        ,  0.        ,  0.26877998],
       [ 0.99925326,  0.49916807,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.25362799],
       [ 0.50428216,  0.51586907,  0.13764165,  0.        ],
       [ 0.        ,  0.87254978,  0.        ,  0.82905441],
       [ 0.        ,  0.23019908,  0.69965787,  0.        ],
       [ 1.55178949,  0.        ,  0.        ,  0.        ]])

In [60]:
data[names != "Joe"] = 7

In [59]:
data

array([[ 7.,  7.,  7.,  7.],
       [ 7.,  7.,  7.,  7.],
       [ 7.,  7.,  7.,  7.],
       [ 7.,  7.,  7.,  7.],
       [ 7.,  7.,  7.,  7.],
       [ 7.,  7.,  7.,  7.],
       [ 7.,  7.,  7.,  7.]])

In [61]:
arr = np.empty((8,4))

In [62]:
for i in range(8):
    arr[i]= i

In [63]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [64]:
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [65]:
arr[[-3, -5, -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [68]:
arr = np.arange(32).reshape(8,4)

In [69]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [70]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [71]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [72]:
arr = np.arange(15).reshape(3,5)

In [73]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [74]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [75]:
arr = np.random.randn(6,3)

In [76]:
arr

array([[ 0.53544949,  0.96944509, -0.66024004],
       [ 0.50927382,  1.85687264, -0.65487972],
       [ 0.14666662,  0.62719237, -0.03866879],
       [-0.1049368 , -1.40720163,  0.54578169],
       [ 0.84213144, -0.62109038,  0.35241358],
       [-0.72263097,  1.69111611,  1.16784241]])

In [77]:
np.dot(arr.T, arr)

array([[  1.80996969,  -0.04069171,  -1.29712284],
       [ -0.04069171,  10.00701346,  -0.89229591],
       [ -1.29712284,  -0.89229591,   2.65220852]])

In [81]:
arr = np.arange(16).reshape(2, 2, 4)

In [79]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [80]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [82]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [83]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [85]:
arr = np.arange(10)

In [86]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [88]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [89]:
x = np.random.randn(8)

In [90]:
y = np.random.randn(8)

In [91]:
x

array([ 0.73143613,  0.48004696, -0.30205059,  0.62999284,  1.02147615,
       -0.14314558,  1.27162242,  0.07182826])

In [92]:
y

array([-0.03241718,  0.91305364,  0.39406687,  1.65950289,  0.17046824,
        0.67257004, -0.04399827, -0.40212071])

In [95]:
np.maximum(x, y)

array([ 0.73143613,  0.91305364,  0.39406687,  1.65950289,  1.02147615,
        0.67257004,  1.27162242,  0.07182826])

In [96]:
arr = np.random.randn(7)* 5

In [97]:
arr

array([-1.81800344,  4.77542767, -4.79969826,  4.98123888, -6.20958493,
       -5.54388976,  2.77690759])

In [98]:
remainder, whole_part = np.modf(arr)

In [99]:
remainder

array([-0.81800344,  0.77542767, -0.79969826,  0.98123888, -0.20958493,
       -0.54388976,  0.77690759])

In [100]:
whole_part

array([-1.,  4., -4.,  4., -6., -5.,  2.])

In [103]:
np.sqrt(arr)

C:\Users\Administrator.MIZMPOLTRW\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan,  2.18527519,         nan,  2.23186892,         nan,
               nan,  1.66640559])

In [104]:
np.sqrt(arr, arr)

C:\Users\Administrator.MIZMPOLTRW\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan,  2.18527519,         nan,  2.23186892,         nan,
               nan,  1.66640559])

In [105]:
arr

array([        nan,  2.18527519,         nan,  2.23186892,         nan,
               nan,  1.66640559])

In [106]:
np.isnan(arr)

array([ True, False,  True, False,  True,  True, False], dtype=bool)

In [107]:
np.log(arr)

array([        nan,  0.78174177,         nan,  0.80283932,         nan,
               nan,  0.51066896])

In [108]:
np.log10(arr)

array([        nan,  0.33950614,         nan,  0.34866868,         nan,
               nan,  0.22178071])

In [110]:
np.ceil(arr)

array([ nan,   3.,  nan,   3.,  nan,  nan,   2.])

In [112]:
np.add(arr, arr)

array([        nan,  4.37055039,         nan,  4.46373784,         nan,
               nan,  3.33281118])

In [113]:
np.subtract(arr, arr)

array([ nan,   0.,  nan,   0.,  nan,  nan,   0.])

In [114]:
np.multiply(arr, arr)

array([        nan,  4.77542767,         nan,  4.98123888,         nan,
               nan,  2.77690759])

## Array Oriented Programming with Arrays

In [115]:
points = np.arange(-5, 5, 0.01)

In [116]:
xs, ys = np.meshgrid(points, points)

In [117]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [118]:
z = np.sqrt(xs**2 + ys**2)

In [119]:
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [120]:
import matplotlib.pyplot as plt

In [123]:
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()

In [128]:
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

Text(0.5,1,'Image plot of $\\sqrt{x^2 + y^2}$ for a grid of values')

In [129]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [131]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [132]:
cond = np.array([True, False, True, True, False])

In [134]:
result = [(x if c else y)
    for x, y, c in zip(xarr, yarr, cond)]

In [135]:
result

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

In [136]:
result = np.where(cond, xarr, yarr)

In [137]:
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [138]:
arr = np.random.randn(4, 4)

In [139]:
arr

array([[ 0.70491096,  0.23848261,  0.29795981, -0.20158545],
       [-1.60441208,  0.08719187,  0.20993384,  0.37588835],
       [-1.64396533,  0.27799736, -1.64836125, -2.85670997],
       [-0.29395056, -0.99171932,  0.96259844,  0.31463472]])

In [140]:
arr>0

array([[ True,  True,  True, False],
       [False,  True,  True,  True],
       [False,  True, False, False],
       [False, False,  True,  True]], dtype=bool)

In [141]:
np.where(arr>0, 2, -2)

array([[ 2,  2,  2, -2],
       [-2,  2,  2,  2],
       [-2,  2, -2, -2],
       [-2, -2,  2,  2]])

In [142]:
np.where(arr>0, 2, arr)

array([[ 2.        ,  2.        ,  2.        , -0.20158545],
       [-1.60441208,  2.        ,  2.        ,  2.        ],
       [-1.64396533,  2.        , -1.64836125, -2.85670997],
       [-0.29395056, -0.99171932,  2.        ,  2.        ]])

## Mathematical and Statistical Methods

In [143]:
arr = np.random.randn(5,4)

In [144]:
arr

array([[-0.55348416,  1.11532579,  1.40754469,  0.5435486 ],
       [ 1.56965399, -0.63047585, -0.39031333, -0.88509016],
       [ 0.03175873, -0.6708999 ,  1.62411547, -1.93434753],
       [-0.16299665, -0.88294659,  0.24327143,  0.55525448],
       [ 0.0219265 ,  0.13305711,  0.40933489,  0.21060976]])

In [145]:
arr.mean()

0.087742362560880485

In [146]:
np.mean(arr)

0.087742362560880485

In [147]:
arr.sum()

1.7548472512176096

In [148]:
np.sum(arr)

1.7548472512176096

In [149]:
arr.mean(axis = 1)

array([ 0.62823373, -0.08405634, -0.23734331, -0.06185433,  0.19373207])

In [150]:
arr.mean(axis = 0)

array([ 0.18137168, -0.18718789,  0.65879063, -0.30200497])

In [151]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [152]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [153]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [154]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [155]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [156]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

## Methods for Boolean Arrays

In [157]:
arr = np.random.randn(100)

In [158]:
arr

array([ -2.34077854e-01,  -5.39197674e-01,   3.26968817e-01,
        -1.28842274e+00,   1.27314642e+00,   3.18276292e-01,
         4.45253274e-01,  -2.61012343e-01,  -7.86829244e-01,
         9.52453884e-01,   5.31532178e-01,  -3.98378212e-01,
         8.39334390e-02,  -4.48239591e-03,   6.94483562e-01,
        -1.90126853e+00,   1.61681098e+00,   5.41074893e-01,
        -1.86251306e-01,   2.42306146e+00,  -6.72373271e-01,
        -1.70127940e+00,  -5.70044186e-01,  -4.62001127e-01,
        -1.34828239e+00,  -1.23807333e-02,  -1.30222821e+00,
         5.44871888e-01,   1.10560178e+00,   8.73667969e-01,
         9.40790378e-01,  -1.53310131e-01,   3.89654430e-02,
         1.64614645e-01,  -3.24588916e-01,   1.53542967e+00,
         8.97061638e-01,  -6.64455962e-01,  -1.24389092e+00,
         2.42559288e+00,   1.61700161e+00,  -8.12382750e-01,
        -8.45598499e-01,   1.24548177e+00,  -7.81600764e-02,
         5.17639820e-01,  -1.09136203e-01,  -3.30474846e-01,
        -1.08592182e+00,

In [159]:
(arr > 0).sum()

50

In [160]:
bools = np.array([False, False, True, False])

In [161]:
bools.any()

True

In [162]:
bools.all()

False

## Sorting


In [163]:
arr = np.random.randn(6)

In [164]:
arr

array([-0.7533121 , -1.47119069,  0.98273827,  0.88992132,  0.16852234,
        0.11133837])

In [165]:
arr = np.random.randn(5, 3)

In [166]:
arr

array([[ 0.09524956,  2.24981509,  1.24463992],
       [ 0.31847688, -0.61830392, -1.63824696],
       [-0.43062371, -0.93302877,  0.21049188],
       [-1.15483394,  0.81443503, -0.59666013],
       [-0.55425992,  2.43756977,  0.07315961]])

In [167]:
arr.sort(1)

In [168]:
arr

array([[ 0.09524956,  1.24463992,  2.24981509],
       [-1.63824696, -0.61830392,  0.31847688],
       [-0.93302877, -0.43062371,  0.21049188],
       [-1.15483394, -0.59666013,  0.81443503],
       [-0.55425992,  0.07315961,  2.43756977]])

In [169]:
large_arr = np.random.randn(1000)

In [171]:
large_arr.sort()

In [172]:
large_arr[int(0.05 * len(large_arr))]

-1.5598324770600593

## Unique and other set logic

In [173]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [174]:
np.unique(names)

array(['Bob', 'Joe', 'Will'],
      dtype='<U4')

In [175]:
ints = np.array([3, 3, 3, 1, 1, 1, 2, 2, 4, 4])

In [176]:
np.unique(ints)

array([1, 2, 3, 4])

In [177]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [178]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [179]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

## File Input and Output with Arrays

In [180]:
arr = np.arange(10)

In [181]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
np.save('some_array', arr)

In [186]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [190]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [191]:
np.savez('array_archive.npz', a=arr, b=arr)

In [193]:
arc = np.load('array_archive.npz')

In [194]:
arc['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
arc['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Linear Algebra

In [198]:
x = np.array([[1., 2., 3. ], [4., 5., 6.]])
y= np.array([[6., 23.],[-1, 7], [8, 9]])

In [199]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [200]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [201]:
np.dot(x, y)

array([[  28.,   64.],
       [  67.,  181.]])

In [2]:
import numpy as np

In [4]:
x = np.array([[1., 2., 3. ], [4., 5., 6.]])
y= np.array([[6., 23.],[-1, 7], [8, 9]])

In [5]:
np.dot(x, np.ones(3))

array([  6.,  15.])

In [1]:
import numpy as np

In [2]:
from numpy.linalg import inv, qr

In [3]:
X = np.random.randn(5, 5)

In [4]:
mat = X.T.dot(X)

In [5]:
inv(mat)

array([[  3.20330618e+00,  -1.62006573e-01,   1.19211725e+00,
         -5.66304451e+00,   3.34540293e+00],
       [ -1.62006573e-01,   7.05257363e-01,   5.62990785e-03,
          4.71384380e-01,  -1.43056461e-01],
       [  1.19211725e+00,   5.62990785e-03,   1.04791406e+00,
         -2.28699843e+00,   1.36036657e+00],
       [ -5.66304451e+00,   4.71384380e-01,  -2.28699843e+00,
          1.06016983e+01,  -6.02193496e+00],
       [  3.34540293e+00,  -1.43056461e-01,   1.36036657e+00,
         -6.02193496e+00,   3.70972060e+00]])

In [8]:
mat.dot(inv(mat))

array([[  1.00000000e+00,  -1.11022302e-16,   0.00000000e+00,
         -3.55271368e-15,   0.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   2.22044605e-16,
         -8.88178420e-16,   6.66133815e-16],
       [ -4.44089210e-16,  -2.77555756e-17,   1.00000000e+00,
         -8.88178420e-16,  -8.88178420e-16],
       [ -2.66453526e-15,   1.66533454e-16,  -6.66133815e-16,
          1.00000000e+00,  -3.99680289e-15],
       [  3.55271368e-15,  -2.22044605e-16,   0.00000000e+00,
          0.00000000e+00,   1.00000000e+00]])

In [9]:
q, r = qr(mat)

In [10]:
r

array([[-10.20487487,   0.71358   ,  -1.56142705,  -2.80185799,
          5.35817217],
       [  0.        ,  -1.8251753 ,   0.42395007,   1.59128973,
          2.45313331],
       [  0.        ,   0.        ,  -1.85017089,   0.11980082,
          0.91629605],
       [  0.        ,   0.        ,   0.        ,  -2.0022911 ,
         -3.43740116],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.12589975]])